openapi: 3.0.3
info:
  title: pgsink
  version: 1.0.0
servers:
- url: http://localhost:8000
paths:
  /api/health/check:
    get:
      tags:
      - Health
      summary: Check Health
      description: Health check for probes
      operationId: Health#Check
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckResponseBody'
              example:
                status: healthy
  /api/imports:
    get:
      tags:
      - Imports
      summary: List Imports
      description: List all imports
      operationId: Imports#List
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Import'
                example:
                - completed_at: "1975-04-12T22:30:25Z"
                  created_at: "2009-06-05T22:54:25Z"
                  error: failed to parse primary key
                  error_count: 2
                  expired_at: "1998-12-14T22:10:24Z"
                  id: 3
                  last_error_at: "1978-02-15T19:04:44Z"
                  rows_processed_total: 5
                  schema: public
                  subscription_id: 74C53540-E974-ABFF-2565-6BF99F9017B2
                  table_name: payments
                  updated_at: "1994-11-27T12:06:47Z"
                - completed_at: "1975-04-12T22:30:25Z"
                  created_at: "2009-06-05T22:54:25Z"
                  error: failed to parse primary key
                  error_count: 2
                  expired_at: "1998-12-14T22:10:24Z"
                  id: 3
                  last_error_at: "1978-02-15T19:04:44Z"
                  rows_processed_total: 5
                  schema: public
                  subscription_id: 74C53540-E974-ABFF-2565-6BF99F9017B2
                  table_name: payments
                  updated_at: "1994-11-27T12:06:47Z"
                - completed_at: "1975-04-12T22:30:25Z"
                  created_at: "2009-06-05T22:54:25Z"
                  error: failed to parse primary key
                  error_count: 2
                  expired_at: "1998-12-14T22:10:24Z"
                  id: 3
                  last_error_at: "1978-02-15T19:04:44Z"
                  rows_processed_total: 5
                  schema: public
                  subscription_id: 74C53540-E974-ABFF-2565-6BF99F9017B2
                  table_name: payments
                  updated_at: "1994-11-27T12:06:47Z"
              example:
              - completed_at: "1975-04-12T22:30:25Z"
                created_at: "2009-06-05T22:54:25Z"
                error: failed to parse primary key
                error_count: 2
                expired_at: "1998-12-14T22:10:24Z"
                id: 3
                last_error_at: "1978-02-15T19:04:44Z"
                rows_processed_total: 5
                schema: public
                subscription_id: 74C53540-E974-ABFF-2565-6BF99F9017B2
                table_name: payments
                updated_at: "1994-11-27T12:06:47Z"
              - completed_at: "1975-04-12T22:30:25Z"
                created_at: "2009-06-05T22:54:25Z"
                error: failed to parse primary key
                error_count: 2
                expired_at: "1998-12-14T22:10:24Z"
                id: 3
                last_error_at: "1978-02-15T19:04:44Z"
                rows_processed_total: 5
                schema: public
                subscription_id: 74C53540-E974-ABFF-2565-6BF99F9017B2
                table_name: payments
                updated_at: "1994-11-27T12:06:47Z"
  /api/subscriptions/current:
    get:
      tags:
      - Subscriptions
      summary: Get Subscriptions
      description: Get current subscription data
      operationId: Subscriptions#Get
      responses:
        "201":
          description: Created response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
              example:
                id: e32ur90j2r
                published_tables:
                - name: payments
                  schema: public
                - name: payments
                  schema: public
  /api/subscriptions/current/actions/add-table:
    post:
      tags:
      - Subscriptions
      summary: AddTable Subscriptions
      description: Add table to publication, relying on an import manager to schedule
        the job
      operationId: Subscriptions#AddTable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionPublishedTable'
            example:
              name: payments
              schema: public
      responses:
        "201":
          description: Created response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
              example:
                id: e32ur90j2r
                published_tables:
                - name: payments
                  schema: public
                - name: payments
                  schema: public
                - name: payments
                  schema: public
  /api/subscriptions/current/actions/stop-table:
    post:
      tags:
      - Subscriptions
      summary: StopTable Subscriptions
      description: Stop a table by removing it from the publication, and expiring
        any import jobs
      operationId: Subscriptions#StopTable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionPublishedTable'
            example:
              name: payments
              schema: public
      responses:
        "202":
          description: Accepted response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
              example:
                id: e32ur90j2r
                published_tables:
                - name: payments
                  schema: public
                - name: payments
                  schema: public
                - name: payments
                  schema: public
                - name: payments
                  schema: public
  /api/tables:
    get:
      tags:
      - Tables
      summary: List Tables
      description: List all tables
      operationId: Tables#List
      parameters:
      - name: schema
        in: query
        description: Comma separated list of Postgres schemas to filter by
        allowEmptyValue: true
        schema:
          type: string
          description: Comma separated list of Postgres schemas to filter by
          default: public
          example: public,payments
        example: public,payments
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Table'
                example:
                - approximate_row_count: 100
                  import_rows_processed_total: 5
                  import_status: unknown
                  name: payments
                  publication_status: active
                  schema: public
                - approximate_row_count: 100
                  import_rows_processed_total: 5
                  import_status: unknown
                  name: payments
                  publication_status: active
                  schema: public
                - approximate_row_count: 100
                  import_rows_processed_total: 5
                  import_status: unknown
                  name: payments
                  publication_status: active
                  schema: public
              example:
              - approximate_row_count: 100
                import_rows_processed_total: 5
                import_status: unknown
                name: payments
                publication_status: active
                schema: public
              - approximate_row_count: 100
                import_rows_processed_total: 5
                import_status: unknown
                name: payments
                publication_status: active
                schema: public
              - approximate_row_count: 100
                import_rows_processed_total: 5
                import_status: unknown
                name: payments
                publication_status: active
                schema: public
  /web/{*filepath}:
    get:
      tags:
      - Web
      summary: Download web/build
      operationId: Web#/web/{*filepath}
      parameters:
      - name: filepath
        in: path
        description: Relative file path
        required: true
      responses:
        "200":
          description: File not found
        "404":
          description: File not found
components:
  schemas:
    CheckResponseBody:
      type: object
      properties:
        status:
          type: string
          description: Status of the API
          example: healthy
          enum:
          - healthy
      example:
        status: healthy
      required:
      - status
    Import:
      type: object
      properties:
        completed_at:
          type: string
          description: Import was completed at this time
          example: "2007-11-21T12:02:53Z"
          format: date-time
        created_at:
          type: string
          description: Import was created at this time
          example: "2008-05-28T08:18:08Z"
          format: date-time
        error:
          type: string
          description: Last import error
          example: failed to parse primary key
        error_count:
          type: integer
          description: Count of error attempts
          example: 2
          format: int64
        expired_at:
          type: string
          description: Import was expired at this time
          example: "2007-07-07T14:42:13Z"
          format: date-time
        id:
          type: integer
          description: Unique ID for the import
          example: 3
          format: int64
        last_error_at:
          type: string
          description: Timestamp of last error, only reset on error
          example: "2007-07-18T23:53:30Z"
          format: date-time
        rows_processed_total:
          type: integer
          description: Count of rows processed
          example: 5
          format: int64
        schema:
          type: string
          description: Postgres table schema
          example: public
        subscription_id:
          type: string
          description: Subscription ID, associating this import to a specific subscription
          example: 233374F1-297F-8711-5FC3-4F6B3731AD63
          format: uuid
        table_name:
          type: string
          description: Postgres table name
          example: payments
        updated_at:
          type: string
          description: Import was last updated at this time
          example: "1997-12-10T06:16:06Z"
          format: date-time
      description: Import job for a Postgres table
      example:
        completed_at: "2004-03-02T17:06:18Z"
        created_at: "2009-03-15T21:55:47Z"
        error: failed to parse primary key
        error_count: 2
        expired_at: "1971-11-03T17:08:24Z"
        id: 3
        last_error_at: "1996-01-03T12:06:35Z"
        rows_processed_total: 5
        schema: public
        subscription_id: CEF3CAF7-AB82-083A-2F08-9497BE6B7488
        table_name: payments
        updated_at: "1998-02-12T22:52:42Z"
      required:
      - id
      - subscription_id
      - schema
      - table_name
      - created_at
      - updated_at
      - error_count
      - rows_processed_total
    Subscription:
      type: object
      properties:
        id:
          type: string
          description: ID of subscription
          example: e32ur90j2r
        published_tables:
          type: array
          items:
            $ref: '#/components/schemas/SubscriptionPublishedTable'
          description: List of published tables
          example:
          - name: payments
            schema: public
          - name: payments
            schema: public
          - name: payments
            schema: public
          - name: payments
            schema: public
      example:
        id: e32ur90j2r
        published_tables:
        - name: payments
          schema: public
        - name: payments
          schema: public
      required:
      - id
      - published_tables
    SubscriptionPublishedTable:
      type: object
      properties:
        name:
          type: string
          description: Postgres table name
          example: payments
        schema:
          type: string
          description: Postgres table schema
          example: public
      description: Table on subscription that is published
      example:
        name: payments
        schema: public
      required:
      - schema
      - name
      - approximate_row_count
      - publication_status
      - import_status
      - import_rows_processed_total
    Table:
      type: object
      properties:
        approximate_row_count:
          type: integer
          description: Table row estimate, using pg_stats
          example: 100
          format: int64
        import_rows_processed_total:
          type: integer
          description: Last active import rows processed total
          example: 5
          format: int64
        import_status:
          type: string
          description: Status of table imports
          example: unknown
          enum:
          - inactive
          - scheduled
          - in_progress
          - error
          - complete
          - expired
          - unknown
        name:
          type: string
          description: Postgres table name
          example: payments
        publication_status:
          type: string
          description: Status of the publication, set to active when table is streaming
          example: active
          enum:
          - inactive
          - active
        schema:
          type: string
          description: Postgres table schema
          example: public
      description: Postgres table, with sync and import status
      example:
        approximate_row_count: 100
        import_rows_processed_total: 5
        import_status: unknown
        name: payments
        publication_status: active
        schema: public
      required:
      - schema
      - name
      - approximate_row_count
      - publication_status
      - import_status
      - import_rows_processed_total
tags:
- name: Web
  description: Web static web content for the UI
- name: Health
  description: Provide service health information
- name: Tables
  description: Expose Postgres tables, and their import/sync status
- name: Subscriptions
  description: Manage a pgsink subscription
- name: Imports
  description: Manage table imports, scoped to the server subscription ID
